openapi: 3.0.1
info:
  title: Open Caching API - CDNI schema extended with SVA Open Caching  objects and properties
  description: 'This is the CDNI schema required to ellaborate an Open Caching API model as exposed by an ISP according to the Streaming Video Alliance (SVA).'
  contact:
    email: guillaume.bichot@broadpeak.tv
  version: 0.4.0
externalDocs:
    description: Find out more
    url: 'https://www.streamingvideoalliance.org/'
components:
  schemas:
    FCI_capabilitytype_sva:
      type: string
      enum: [FCI.Capacity.sva, FCI.Metadata, FCI.AuthTypes.sva]
    FCI_genericbase:
      type: object
      description: 'adding properties to the FCI_genericbase object'
      required:
        - capability-type
        - capability-value
      properties:
        capability-type:
          oneOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI_capabilitytype'
            - $ref: '#/components/schemas/FCI_capabilitytype_sva'
        capability-value:
          oneOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI.DeliveryProtocol'
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI.AcquisitionProtocol'
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI.RedirectionMode'
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI.Logging'
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/FCI.RedirectTarget'
            - $ref: '#/components/schemas/FCI.Metadata'
            - $ref: '#/components/schemas/FCI.Capacity'
            - $ref: '#/components/schemas/FCI.AuthTypes'
          discriminator: 
            propertyName: capability-type
        footprints:
          type: array
          description: 'List of CDNI Footprint objects (from the "CDNI Metadata Footprint Types" registry [RFC8006])'
          items:
            $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Footprint'
    FCI.Metadata:
      type: object
      description: 'extension of CDNI FCI.Metadata'
      required:
        - metadata
      properties:
        metadata:
          description: 'List of supported CDNI GenericMetadata types. List of strings corresponding to entries from the "CDNI
         Payload Types" registry [RFC7736] that correspond to CDNI GenericMetadata objects. An empty list MUST be interpreted as 
         "no GenericMetadata types are supported", i.e., "only structural metadata and simple types are supported"; otherwise, the list
         must be interpreted as containing "the only GenericMetadata types that are supported" (in addition to structural metadata and simple types) [RFC8006].'
          type: array
          items:
            $ref: '#/components/schemas/MI_payloadtype'
    FCI.AuthTypes:
      type: object
      required:
        - auth-types
      properties:
        authe-types:
          type: array
          items: 
            $ref: '#/components/schemas/MI_authtype'
        autho-types:
          type: array
          items: 
            $ref: '#/components/schemas/MI_authtype'
    FCI.Capacity:
      description: 'capacity capabilities'
      oneOf:
        - $ref: '#/components/schemas/MI.Capacity.sva'
# MI extensions
    MI.HostIndex:
      type: object
      description: 'The HostIndex object is the entry point into the CDNI Metadata hierarchy.  It contains an array of HostMatch objects. 
      An incoming content request is checked against the hostname (or IP address) specified by each of the listed HostMatch objects to find 
      the HostMatch object that applies to the request'
      required:
        - hosts
      properties:
        hosts:
          description: 'Array of HostMatch objects.  Hosts (HostMatch objects) MUST be evaluated in the order they appear, and the first HostMatch object that matches the content request being processed MUST be used'
          type: array
          items:
            $ref: '#/components/schemas/MI_hostmatch'
    MI_hostmatch:
      oneOf:
        - $ref: '#/components/schemas/MI.HostMatch'
        - $ref: '#/components/schemas/MI_link'
    MI.HostMatch:
      type: object
      required:
        - host
        - host-metadata
      properties:
        host:
          allOf:
            - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_endpoint'
          description: 'Hostname or IP address and optional port to match against the requested host, i.e., the host and port as described in [RFC3986]. 
          In order for a hostname or IP address in a content request to match the hostname or IP address in the "host" property, 
          the value from the content request when converted to lowercase MUST be identical to the value of the "host" property when converted to lowercase.  
          All implementations MUST support IPv4 addresses encoded as specified by the "IPv4address" rule in Section 3.2.2 of [RFC3986]. 
          IPv6 addresses MUST be encoded in one of the IPv6 address formats specified in [RFC5952], although receivers MUST support 
          all IPv6 address formats specified in [RFC4291]. Hostnames MUST conform to the Domain Name System (DNS) syntax defined in [RFC1034] and [RFC1123].  
          Internationalized Domain Names (IDNs) must first be transformed to the A-label form [RFC5890] as per [RFC5891]'
        host-metadata:
          $ref: '#/components/schemas/MI_HostMetadata'
          description: 'CDNI Metadata to apply when delivering content that matches this host'
    MI_HostMetadata:
      oneOf:
        - $ref: '#/components/schemas/MI.HostMetadata'
        - $ref: '#/components/schemas/MI_link'
    MI.HostMetadata:
      type: object
      description: 'A HostMetadata object contains the CDNI Metadata properties for content served for a particular host (defined in the HostMatch object) 
      and possibly child PathMatch objects.'
      required:
        - metadata
      properties:
        metadata: 
          type: array
          items:
            $ref: '#/components/schemas/MI.GenericMetadata'
        paths:
          type: array
          description: 'Description: Path-specific rules.  Path patterns (PathMatch objects) MUST be evaluated in the order they appear, 
          and the first (and only the first) PathMatch object that matches the content request being processed MUST be used'
          items:
            $ref: '#/components/schemas/MI_PathMatch'
    MI_PathMatch:
      oneOf:
        - $ref: '#/components/schemas/MI.PathMatch'
        - $ref: '#/components/schemas/MI_link'
    MI.PathMatch:
      type: object
      description: 'A PathMatch object contains a PatternMatch object with a path to match against a resource URI path, 
      as well as how to handle URI query parameters.  The PathMatch object also contains a PathMetadata object with GenericMetadata to apply 
      if the resource URI matches the pattern within the PatternMatch object.'
      required:
        - path-pattern
        - path-metadata
      properties:
        path-pattern:
          $ref: '#/components/schemas/MI_PatternMatch'          
        path-metadata:
          $ref: '#/components/schemas/MI_PathMetadata'
    MI_PatternMatch:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.PatternMatch'
    MI_PathMetadata:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.PathMetadata'
    MI.PathMetadata:
      type: object
      description: 'A PathMetadata object contains the CDNI Metadata properties for content requests that match against 
      the associated URI path (defined in a PathMatch object). Note that if DNS-based redirection is employed, then 
      a dCDN will be unable to evaluate any metadata at the PathMetadata level or below because only the hostname of the content request 
      is available at Request Routing time.  
      dCDNs SHOULD still process all PathMetadata for the host before responding to the redirection request to detect if any unsupported metadata is specified.  
      If any metadata not supported by the dCDN is marked as mandatory-to-enforce, the dCDN SHOULD NOT accept the content redirection request, 
      in order to avoid receiving content requests that it will not be able to satisfy/serve.'
      required:
        - metadata
      properties:
        metadata:
          type: array
          items:
            $ref: '#/components/schemas/MI_GenericMetadata'
        paths:
          type: array
          description: 'Description: Path-specific rules.  Path patterns (PathMatch objects) MUST be evaluated in the order they appear, 
          and the first (and only the first) PathMatch object that matches the content request being processed MUST be used'
          items:
            $ref: '#/components/schemas/MI_PathMatch'
    MI_DeliveryAuthorizatione:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.DeliveryAuthorization'
    MI.DeliveryAuthorization:
      type: object
      description: 'Delivery authorization defines authorization methods for the delivery of content to User Agents.'
      properties:
        delivery-auth-methods:
          description: 'Options for authorizing content requests. Delivery for a content request is authorized if any one of the authorization methods
          in the list is satisfied for that request.'
          type: array
          items:
            $ref: '#/components/schemas/MI_Auth'
    MI_Auth:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.Auth'
    MI.Auth:
      type: object
      description: 'An Auth object defines authentication and authorization methods to be used during content acquisition and content delivery respectively'
      properties:
        auth-type:
          $ref: '#/components/schemas/MI_authtype'
        auth_value:
          oneOf:
            - $ref: '#/components/schemas/MI_UriSigning'
            - $ref: '#/components/schemas/MI_HeaderAuth'
          discriminator: 
            propertyName: auth-type 
    MI_authtype:
      type: string
      enum: [MI.HeaderAuth, MI.AWSv4Auth, MI.UriSigning]
    MI_HeaderAuth:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.HeaderAuth'
    MI.HeaderAuth:
      type: object
      description: 'Header based authentication is used to pass an HTTP header (secret-name) and value (secret-value) to a uCDN when requesting content. The header name and value are agreed upon between parties out of band.'
      required:
        - header-name
        - header-value
      properties: 
        header-name:
          type: string
          description: 'Name of the authentication header'
        header-value:
          description: 'Value of the authentication header (typically a pre-shared key).'
          type: string
      example:
        value: {
          "auth-type": "headerauth",
          "auth-value":
          {
           "header-name": "X-Origin-Auth",
           "header-value": "SECRETKEYJKSDHFSIUHKWRGHFUI4UFH78HW4NF7"
           }
          }
    MI_AWSv4Auth:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.AWSv4Auth'
    MI.AWSv4Auth:
      type: object
      description: 'Allows for the specification of a set of headers to be added to requests that are forwarded to an origin to enable Amazon Web Services (AWS) authentication, as documented by AWS (See Specifications & Standards References)'
      required:
        - access-key-id
        - secret-access-key
        - aws-region
        - aws-service
        - host-name
      properties: 
        access-key-id:
          description: 'The preconfigured ID of the pre-shared authorization secret.'
          type: string
        secret-access-key:
          description: 'The pre-shared authorization secret, which is the basis of building the signature. This is a secret key that should not be disclosed; it should be protected by some mechanism while resident in configuration objects.'
          type: string
        aws-region:
          description: 'The AWS region name that is hosting the service and shares the key ID and corresponding pre-shared secret.'
          type: string
        aws-service:
          description: 'The AWS service name that is serving the upstream requests.'
          type: string
        host-name:
          description: 'The host name to use as part of the signature calculation.'
          type: string
    MI_UriSigning:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.UriSigning'
    MI.UriSigning:
      type: object
      description: 'The UriSigning Metadata object contains information to enable URI signing and verification by a dCDN. According to section 4.4 of "URI Signing for CDN Interconnection (CDNI) https://datatracker.ietf.org/doc/html/draft-ietf-cdni-uri-signing  '
      properties:
        enforce: 
          type: boolean
          default: true
          description: 'URI Signing enforcement flag.  Specifically, this flag indicates if the access to content is subject to URI Signing. URI Signing requires the dCDN to ensure that the URI is signed and verified before delivering content.  Otherwise, the dCDN does not perform verification, regardless of whether or not the URI is signed.'
        issuers:
          type: array
          items:
            type: string
          description: 'A list of valid Issuers against which the Issuer claim in the signed JWT may be verified.'
        package-attribute:
          type: string
          description: 'The name to use for the URI Signing Package. Default name is "URISigningPackage"'
        jwt-header:
          type: string
          description: 'The header part of JWT that is used for generating or verifying a signed JWT when the JWT token in the URI Signing Package does not contain a header part.  By default, the header is assumed to be included in the JWT token.'
      example:
        value: {
         "enforce": true,
         "issuers": ["csp", "ucdn1", "ucdn2"],
         "package-attribute": "usp",
         "jwt-header":
           {
               "alg": "ES256",
               "kid": "P5UpOv0eMq1wcxLf7WxIg09JdSYGYFDOWkldueaImf0"
           }
       }
    MI_link:
      type: object
      description: ' Link object can be used in place of any of the objects described above.  Link objects can be used to avoid duplication 
      if the same metadata information is repeated within the metadata tree.  When a Link object replaces another object, its "href" property 
      is set to the URI of the resource and its "type" property is set to the CDNI Payload Type of the object it is replacing. dCDNs can detect 
      the presence of a Link object by detecting the presence of a property named "href" within the object.  This means that GenericMetadata types MUST NOT contain 
      a property named "href" because doing so would conflict with the ability for dCDNs to detect Link objects being used to reference a GenericMetadata object.'
      required:
        - href
      properties:
        href:
          type: string
          format: Uri
        type:
          $ref: '#/components/schemas/MI_metadatatype'
    MI_metadatatype:
      allOf:
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI_payloadtype'
        - $ref: '#/components/schemas/MI_payloadtype'
    MI_payloadtype:
      type: string
      enum: [MI.HeaderAuth, MI.AWSv4Auth, MI.UriSigning, MI.AllowCompress]
    MI_metadatavalue:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI_payloadvalue'
    MI_payloadvalue:
      oneOf:
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.SourceMetadata'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Source'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.LocationACL'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.LocationRule'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Footprint'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.TimeWindowACL'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.TimeWindowRule'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.TimeWindow'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.ProtocolACL'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.ProtocolRule'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Cache'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.Grouping'
        - $ref: './SVA_OC_CDNI_openapi.yaml#/components/schemas/MI.FallbackTarget'                     
        - $ref: '#/components/schemas/MI.DeliveryAuthorization'
        - $ref: '#/components/schemas/MI.Auth'
        - $ref: '#/components/schemas/MI.AWSv4Auth'
        - $ref: '#/components/schemas/MI.HeaderAuth'
        - $ref: '#/components/schemas/MI.UriSigning'
        - $ref: '#/components/schemas/MI.AllowCompress'
        - $ref: '#/components/schemas/MI.CachePolicy'
    MI_GenericMetadata:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.GenericMetadata'    
    MI.GenericMetadata:
      type: object
      description: 'GenericMetadata object extended by SVA'
      required:
        - generic-metadata-type
        - generic-metadata-value
      properties:
        generic-metadata-type:
          $ref: '#/components/schemas/MI_metadatatype'
        generic-metadata-value:
           $ref: '#/components/schemas/MI_metadatavalue'
        mandatory-to-enforce:
          type: boolean
          description: 'Flag identifying whether or not the enforcement of the property metadata is required.'
          default: true
        safe-to-redistribute:
          type: boolean
          description: 'Flag identifying whether or not the property metadata can be safely redistributed without modification.'
          default: true
        incomprehensible:
          type: boolean
          description: 'Flag identifying whether or not any CDN in the chain of delegation has failed to understand and/or failed to properly transform this metadata object.  Note: This flag only applies to metadata objects whose safe-to-redistribute property has a value of False.'           
    MI_AllowCompress:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.AllowCompress'
    MI.AllowCompress:
      type: object
      properties:
        allow-compress:
          type: boolean
          default: false
      example:
        value: {
                    "allow-compress": "true"
                }
    MI_CachePolicy:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.CachePolicy'
    MI.CachePolicy:
      type: object
      properties:
        internal:  
          description: 'This property is used to specify the (internal) cache control policy to be used by the dCDN.The value of the cache policy is in seconds. “5”, as an example for a five second cache. The following special values are also supported: "as-is", "no-cache", "no-store". If not used, default to use the cache control policy specified in the HTTP response from the uCDN.' 
          oneOf:
            - type: string
            - type: string
              enum: [as-is, no-cache, no-store]
        external:  
          description: 'This property is used to specify the (external) cache control policy to be used by clients of this dCDN. The value of the cache policy is in seconds. The following special values are also supported: "as-is", "no-cache", "no-store". “no-cache”.The value of the cache policy is in seconds. The following special values are also supported: "as-is", "no-cache", "no-store". “no-cache”. If not used, default to use the cache control policy specified in the HTTP response from the uCDN.'
          oneOf:
            - type: string
            - type: string
              enum: [as-is, no-cache, no-store]
        force:  
          description: 'If set to "True", the metadata interface cache policy defined in the MI.CachePolicy will override any cache control policy set in the response from the uCDN. If set to "False", the MI.CachePolicy is only used if there is no cache control policy provided in the response from the uCDN. Default is False, which will apply the MI.CachePolicy only if no policy is provided in the response from the uCDN.'
          type: boolean
      example:
        value:  {
                  "internal": "as-is",
                  "external": "no-cache",
                  "force": "true"
                  }

    MI_ComputedCacheKey:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.ComputedCacheKey'
    MI.ComputedCacheKey:
      type: object
      required:
        - expression
      properties:
        expression:
          description: 'An expression using CDNI-MEL to dynamically construct the cache key from elements of the HTTP request and/or response'
          type: string
      example:
        value: {
    "expression" : "$req.h.X-Cache-Key",
  }
    MI_CrossoriginPolicy:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.CrossoriginPolicy'
    
    MI.CrossoriginPolicy:
      type: object
      description: 'Controls the dynamically generated CORS headers'
      required:
        - allow-origin
      properties:
        allow-origin:
          description: 'Validation of simple CORS requests' 
          type: Object
          required:
          - allow-list
          - wildcard-return
          properties:
            allow-list:
              description: 'List of valid URLs (only scheme and hostname) that will be used to match the request origin header.'
              type: array
              items: 
                $ref: '#/components/schemas/MI_PatternMatch'
            wildcard-return:
              description: 'If true, the OCN will include a wildcard (*) in the Access-Control-Allow-Origin response header. If false, the OCN will reflect back the request Origin header in the Access-Control-Allow-Origin response header.'
              type: boolean
        expose-headers:
          description: 'A list of values the OCN will include in the Access-Control-Expose-Headers response header to a preflight request.'
          type: array
          items:
            type: string
        allow-methods:
          description: 'A list of values the OCN will include in the Access-Control-Allow-Methods response header to a preflight request.'
          type: array
          items:
            type: string
        allow-headers:
          description: 'A list of values the OCN will include in the Access-Control-Allow-Headers response header to a preflight request.'
          type: array
          items:
            type: string
        allow-credentials:
          description: 'The value the OCN will include in the Access-Control-Allow-Credentials response header to a preflight request.'
          type: boolean
        max-age:
          description: The value the OCN will include in the Access-Control-Max-Age response header to a preflight request.
          type: integer
      example:
        value: {
              "allow-origin": {
                "allow-list": {
                  "pattern": "*://sourcepage.example.com"},
                "wildcard-return": false
              },
              "allow-methods": ["GET","POST"],
              "allow-credentials": true,
              "allow-headers": ["X-PINGOTHER","Content-Type"],
              "expose-headers": ["X-User","Authorization"],
              "max-age": 3600
            }
    MI_NegativeCachePolicy:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.NegativeCachePolicy'
    MI.NegativeCachePolicy: 
      type: object
      description: 'Allows for the configuration of caching policies based on error response codes received from the origin.'
      required:
        - cache-policy
      properties:
        error-codes:
          description: 'Array of HTTP response error status codes (https://tools.ietf.org/html/rfc7231#page-47), that if returned from the uCDN, will be cached using the cache policy defined in MI.CachePolicy. by default the policy expressed in RFC8006 is applied'
          type: array
          items:
            type: string
            enum: [404, 503, 504]
        cache-policy:
          description: 'MI.CachePolicy to apply to the HTTP response error status codes returned by the uCDN.'
          $ref: '#/components/schemas/MI_CachePolicy'
      example:
        value: {
        "error-codes": ["404", "503", "504"],
        "cache-policy": {
          "internal": "5",
          "external": "no-cache",
          "force": "true"
        }
      }
    MI_NonCacheablePolicy:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.NonCacheablePolicy'
    MI.NonCacheablePolicy:
      type: object
      description: 'allows a client request to be set as non cacheable.  It is expected that this feature will be used to allow clients to test the fill path to the uCDN.'
      properties:
        non-cacheable:
          description: 'A Boolean value that can activate the feature for a given client request.  It is expected that this feature will be used within a ProcessingStages to allow a client request to be marked to bypass a cache.'
          type: boolean
          default: false
    MI_PrivateFeatureList:
      oneOf:
        - $ref: '#/components/schemas/MI_link'
        - $ref: '#/components/schemas/MI.PrivateFeatureList'
    MI.PrivateFeatureList:
    MI.Stages:
      type: object
      properties:
        stages:
          type: array
          items:
            $ref: '#/components/schemas/MI_stage'
    MI_stage:
      type: object
      properties:
        stage-type:
          $ref: '#/components/schemas/MI_stagetype'
        stage-value:
          oneOf:
            - $ref: '#/components/schemas/MI_stagerule_replaceheader'
    MI_stagerule_replaceheader:
      type: object
      properties:
        header-name:
          type: string
          description: 'name of teh HTTP header to act upon'
        header-value:
          type: string
          description: 'the value that replace the existing one. Note that the value may be an emmpty string that indicates the header can be removed'
    MI_stagetype:
      type: string
      enum: [clientRequest, originRequest, originResponse, clientResponse]
    
    MI.Capacity:
      type: object
      description: 'capacity interface configuration'
      required:
        - capacities
      properties:
        capacities:
          description: 'An array with footprints and associated capacity type to listen'
          type: array
          items:
            $ref: '#/components/schemas/MI_capacity'
    MI_capacity:    
      type: object
      description: 'a footprint entry associated with a capacity configuration.'
      required:
        - capacity-type
      properties:  
        footprint:
          description: 'the surrogates caches concerned by the capacity inquiry/monitoring'
          type: array
          items:
            $ref: '#/components/schemas/MI.Footprint'
        capacity-type:
          description: 'the type of capacity'
          type: array
          items:
            $ref: '#/components/schemas/MI_capacitytype_sva'
    MI_capacitytype_sva:
      type: object
      properties:
        source:
          description: 'capacity source'
          type: string
          enum: [storage, bandwidth]
        unit:
          type: string
          enum: [ratio, kbps, kB]